float *returnVector(int );
float **returnMatrix(int , int );
void freeMatrix(float **, int );
float mean(float *, int );
float covariance(float *, float *, int );
float correlation(float *, float *, int );
float **matrixTranspose(float **, int , int );
float **matrixMultiplication(float **, float **, int , int , int , int );
float *rowMeans(float **, int , int );
float *columnMeans(float **, int , int );
float **covarianceMatrix(float **, int , int );
float determinant(float **, int );
void printVector(float *, int );
void printMatrix(float **, int , int );
void matrixRandom(float **, int , int );
void vectorRandom(float *, int );
